name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  with-latest:
    strategy:
      matrix:
        os:
          [
            ubuntu-24.04,
            macos-15,
            windows-2025,
            ubuntu-24.04-arm,
            macos-26-intel,
          ]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./
      - run: seiton --version

  with-version:
    strategy:
      matrix:
        os:
          [
            ubuntu-24.04,
            macos-15,
            windows-2025,
            ubuntu-24.04-arm,
            macos-26-intel,
          ]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./
        with:
          version: "0.9.19"
      - run: test "$(seiton --version)" = "seiton version 0.9.19"

  with-version-v-prefix:
    strategy:
      matrix:
        os:
          [
            ubuntu-24.04,
            macos-15,
            windows-2025,
            ubuntu-24.04-arm,
            macos-26-intel,
          ]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./
        with:
          version: "v0.9.19"
      - run: test "$(seiton --version)" = "seiton version 0.9.19"
